name: CI/CD Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: > 
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Installer les dépendances backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 4. Lancer les tests backend
      - name: Run backend tests
        run: |
          cd backend
          npm test

      # 5. Construire les images Docker
      - name: Build Docker images
        run: |
          docker-compose build

      # 6. Pousser les images sur Docker Hub
      - name: Push Docker images
        run: |
          docker-compose push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
